module.exports={
  publicPath:'/miaomiao',
  devServer:{
    proxy:{
      '/api2':{
        target:"http://localhost:3000",
        changeOrigin:true
      },
      '/api':{
        target:"http://37.97.33.179",
        changeOrigin:true
      }
    }
  }
}
